# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor', models.CharField(default='Unknown', max_length=100)),
                ('description', models.TextField(default='Unkown')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('published', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
