# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemChosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='problem',
            name='contributor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='problemchosen',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem'),
        ),
    ]
