# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20170719_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemchosen',
            name='chosen_date',
            field=models.DateField(auto_now=True),
        ),
    ]
